# YAML
forecast_post_ceiling_cost_SR: 0.13
percentage_vol_target: 25.0
notional_trading_capital: 50000
base_currency: "GBP"

trading_rules:
  ewmac2_8:
     function: systems.provided.futures_chapter15.rules.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 2
         Lslow: 8

  ewmac4_16:
     function: systems.provided.futures_chapter15.rules.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 4
         Lslow: 16

  ewmac8_32:
     function: systems.provided.futures_chapter15.rules.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 8
         Lslow: 32

  ewmac16_64:
     function: systems.provided.futures_chapter15.rules.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 16
         Lslow: 64

  ewmac32_128:
     function: systems.provided.futures_chapter15.rules.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 32
         Lslow: 128

  ewmac64_256:
     function: systems.provided.futures_chapter15.rules.ewmac
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 64
         Lslow: 256

  carry:
     function: systems.provided.futures_chapter15.rules.carry2
     data:
         - "rawdata.raw_carry"
     other_args:
         smooth_days: 90

forecast_cap: 20.0

forecast_div_multiplier:
  BUXL_fsb: 1.411996413029748
  CAD_fsb: 1.3685328579274758
  CRUDE_W_fsb: 1.3803391275901382
  EUROSTX_fsb: 1.3672026551109435
  GOLD_fsb: 1.4014632432146945
  NASDAQ_fsb: 1.4804546003729513
  NZD_fsb: 1.3797796010154417
  US10_fsb: 1.3521652338321637
forecast_mapping: {}
forecast_scalars:
  carry: 30.0
  ewmac16_64: 3.75
  ewmac2_8: 10.6
  ewmac32_128: 2.65
  ewmac4_16: 7.5
  ewmac64_256: 1.87
  ewmac8_32: 5.3
forecast_weights:
  BUXL_fsb:
    carry: 0.596736394723965
    ewmac16_64: 0.0878970358715876
    ewmac2_8: 7.241539432309246e-18
    ewmac32_128: 0.09535855230198806
    ewmac4_16: 0.0503995617283892
    ewmac64_256: 0.09944517365947338
    ewmac8_32: 0.07016328171459416
  CAD_fsb:
    carry: 0.6332748356842279
    ewmac16_64: 0.09252287005355384
    ewmac2_8: 5.807300252821356e-18
    ewmac32_128: 0.10194707371598127
    ewmac4_16: 5.8080445967453715e-18
    ewmac64_256: 0.10625266827102738
    ewmac8_32: 0.06600255227520459
  CRUDE_W_fsb:
    carry: 0.6261414754154123
    ewmac16_64: 0.08667488430067995
    ewmac2_8: 1.7718048294845803e-18
    ewmac32_128: 0.09482767960010308
    ewmac4_16: 0.027074254752028196
    ewmac64_256: 0.09842791519682034
    ewmac8_32: 0.06685379073495352
  EUROSTX_fsb:
    carry: 0.6341687943617029
    ewmac16_64: 0.0892084560582206
    ewmac2_8: 2.9778483085324514e-17
    ewmac32_128: 0.09944927851110606
    ewmac4_16: 0.008129425037247324
    ewmac64_256: 0.10412821059779344
    ewmac8_32: 0.06491583543392739
  GOLD_fsb:
    carry: 0.6025355840939072
    ewmac16_64: 0.09034476747505714
    ewmac2_8: 1.2791377740217535e-17
    ewmac32_128: 0.09880186104684606
    ewmac4_16: 0.0343626960392203
    ewmac64_256: 0.10349968958355167
    ewmac8_32: 0.07045540176142125
  NASDAQ_fsb:
    carry: 0.5014749080339328
    ewmac16_64: 0.10623702995320888
    ewmac2_8: 4.2004190208021345e-18
    ewmac32_128: 0.11483817560842777
    ewmac4_16: 0.07208994318084337
    ewmac64_256: 0.11937100460139585
    ewmac8_32: 0.085988938622191
  NZD_fsb:
    carry: 0.6191794911994032
    ewmac16_64: 0.09577779726599538
    ewmac2_8: 3.0420359254680902e-18
    ewmac32_128: 0.1056453461424564
    ewmac4_16: 3.043535450114174e-18
    ewmac64_256: 0.11014853406792911
    ewmac8_32: 0.06924883132421406
  US10_fsb:
    carry: 0.6526962780286482
    ewmac16_64: 0.08748293064478227
    ewmac2_8: 5.6855086724452466e-18
    ewmac32_128: 0.09719562111825525
    ewmac4_16: 2.8240666457962903e-18
    ewmac64_256: 0.10107069374298412
    ewmac8_32: 0.061554476465329556
instrument_div_multiplier: 2.208335421957209
instrument_weights:
  BUXL_fsb: 0.08786201537808891
  CAD_fsb: 0.09652800291998172
  CRUDE_W_fsb: 0.14038197243076855
  EUROSTX_fsb: 0.17227743291827244
  GOLD_fsb: 0.14628312513578456
  NASDAQ_fsb: 0.17227743291827244
  NZD_fsb: 0.09652800291998172
  US10_fsb: 0.08786201537884793

start_date: 2000-01-01

#ignore_instruments:

#
# duplicated/excluded instruments are ignored in backtests
# we still collect price data for them in production, do rolls etc
# this is to avoid double counting of basically the same instrument
# anything in the 'exclude' list is ignored in backtests
# we use the 'include section to match up for reporting when deciding which to trade
# Be careful when swapping between instruments, a bit dangerous if a position is held...
# You can override this by modifying the backtest config .yaml file used in either sim or production
duplicate_instruments:
  include:
    kospi: 'KOSPI'
  exclude:
    kospi: 'KOSPI_mini'
exclude_instrument_lists:
  # ignore_instruments are ignored in backtests
  # we still collect price data for them in production, do rolls etc
  # You can override this by modifying the backtest config .yaml file used in eithier sim or production
  # If you want to ignore because a duplicate market, use duplicate_instruments
  # If you want to include in sim data, but not actually trade, use trading_restrictions
  ignore_instruments:
    - 'KOSPI' # not supported on IG
  #
  # Here we put stuff we can't trade, but for which we still want to bring in prices in sim
  # For the dynamically optimised strategy this list will be used in sim as 'don't trade'
  # For static strategies, you will probably want to set these to zero instrument weights
  # In production, things here will be added to the 'reduce_only' list of instruments
  # NOTE: This will be regionally biased, you will probably want to override this in private_config.yaml
  #
  trading_restrictions:
    - US-DISCRETE
    - US-ENERGY
    - US-FINANCE
    - US-HEALTH
    - US-INDUSTRY
    - US-MATERIAL
    - US-PROPERTY
    - US-REALESTATE
    - US-STAPLES
    - US-TECH
    - US-UTILS
  # These are markets that are too expensive or illiquid to actually trade
  # For the dynamically optimised strategy this list will be used in sim as 'don't trade'
  # For static strategies, you will probably want to set these to zero instrument weights
  # In production, things here will be added to the 'reduce_only' list of instruments
  # Run interactive controls to get a list of suggested markets here
  # To override this list, change in sim .yaml config (sim) and private_config.yaml (production)
  bad_markets:
    - ALUMINIUM
    - BBCOMM
    - CHEESE
    - DJSTX-SMALL
    - EU-BANKS
    - EU-CHEM
    - EU-CONSTRUCTION
    - EU-DIV30
    - EU-FOOD
    - EU-HEALTH
    - EU-INSURE
    - EU-TRAVEL
    - FTSEINDO
    - INR
    - KOSPI_mini
    - KRWUSD
    - MILK
    - MILKDRY
    - MSCIASIA
    - NOK
    - SGD
    - US-DISCRETE
    - US-REALESTATE
    - USIRS5
