instruments: [
   "DOW_fsb",
   "BTP_fsb",
   "BUXL_fsb",
   "CAD_fsb",
   "COFFEE_fsb",
   "CRUDE_W_fsb",
   "EUR_fsb",
   "EUROSTX_fsb",
   "GILT_fsb",
   "GOLD_fsb",
   "JPY_fsb",
   "NASDAQ_fsb",
   "NIKKEI_fsb",
   "NZD_fsb",
   "SOYOIL_fsb",
   "US10_fsb",
]

#
use_forecast_scale_estimates: True
#
forecast_scalar_estimate:
   pool_instruments: True
#
# forecast combination
#
use_forecast_weight_estimates: True
use_forecast_div_mult_estimates: True

#
forecast_correlation_estimate:
   pool_instruments: True
#
use_instrument_weight_estimates: True
use_instrument_div_mult_estimates: True

forecast_weight_estimate:
   n_threads: 8


