#instruments: ['BUXL','CHF','DAX','CRUDE_W','GOLD','NASDAQ','EURGBP','US30','SOYOIL']
#instruments: ['GOLD', 'CARBON', 'BUXL', 'EUROSTX', 'LEANHOG', 'CHF', 'OJ', 'COPPER', 'RUSSELL', 'COCOA_NY', 'CRUDE_W', 'EURGBP']
#instruments: ["NASDAQ","US30","GOLD","DAX","BUXL","CARBON","HANG","GILT","CRUDE_W","EUROSTX"]
#instruments: ["NASDAQ","US30","GOLD","DAX","BUXL","CARBON","NIKKEI","GILT","CRUDE_W","LEANHOG"]
#instruments: [
#   "NASDAQ","EUROSTX","NIKKEI",
#   "US30","BUXL","GILT",
#   "CAD","NZD","GBP",
#   "GOLD","CARBON","CRUDE_W","COPPER","SOYOIL"
#]
instruments: [
    "BUXL_fsb",
    "CAD_fsb",
    "CRUDE_W_fsb",
    "EUROSTX_fsb",
    "GOLD_fsb",
    "NASDAQ_fsb",
    "NZD_fsb",
    "US10_fsb",
]

#
use_forecast_scale_estimates: True
#
forecast_scalar_estimate:
   pool_instruments: True
#
# forecast combination
#
use_forecast_weight_estimates: True
use_forecast_div_mult_estimates: True

#
forecast_correlation_estimate:
   pool_instruments: True
#
use_instrument_weight_estimates: True
use_instrument_div_mult_estimates: True




