# YAML
# This is an example of the variables you need to set
# in your private_config.yaml file in the ~/pysystemtrade/private folder
#

####################################################################################################
#
# OPTIONAL: Not in defaults.yaml
#

# email address variables - If missing emails won't be sent and you will have to check logs/echos

email_address: 'some_address@server.com' # add your address here
email_pwd: 'terrible_mash_of_stuff_for_security' # your password
email_server: 'the_outgoing_smtp_server' # the smtp server
# email_port: 587 # for future use: currently hardcoded at 587.
# email_security: 'SSL or TLS' # for future use

####################################################################################################
#
# OVERRIDES: In defaults.yaml and will override
#

#Mongo db variables

mongo_host: 'localhost' # can be elsewhere
mongo_db: 'production' # fits with all the documentation

####################################################################################################
#
# OPTIONAL: but required for pysystemtrade-fsb fork
#

# if you wish to import Barchart csv price data, or build roll calendars BEFORE importing the prices
# into mongo, set this
barchart_path: '/path/to/your/barchart/price/data'

# if you wish to get free FX price updates from Alpha Vantage, set this
alpha_vantage_api_key: 'ABC123XYZ987000000000'

# IG connection params

# account type, either 'demo' or 'live'
ig_acc_type: 'demo'
# your IG username. will be different for live and demo
ig_username: 'iguser'
# your IG password. will be different for live and demo
ig_password: 's3cr3t1234'
# your IG API key. will be different for live and demo
ig_api_key: 'abcdefgh1234567890'
# your IG account number. will be different for live and demo
ig_acc_number: 'ABC123'
