name: Format Python Code
on: [push, pull_request]
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@23.11.0  # <--- Changed this line
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: auto-format python code with black"
